### ISSUE TITLE
Hosting site

### ISSUE THREAD

**Issue by LaviniaDodu** [LaviniaDodu/portafoglio#1]
I'm trying to public a web site made with Laravel, I followed the Github Doc but the only thing tha it showing me online is the ReadMe page!
If anybody can help me I would be more than gratefull.

**Comment by Magicianred** [comment]
What guide you have follow? 
You have try one free hosting for laravel? 
https://geekflare.com/laravel-hosting/amp/

**Comment by LaviniaDodu** [comment]
Previously I wanted to deploy my project using GitHub Page (and I understood that i can't do it ), than  I ended up publishing it with DigitalOcean and OVH. 
Anyway, you're response is very usefull for me and definitely use it with my next projects , so thank you a lot !
